# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Clouni application

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.6
      uses: actions/setup-python@v3
      with:
        python-version: "3.6"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-ansible.txt
        pip install -r requirements.txt; fi
    - name: Install dependencies
      run: |
        git clone https://github.com/bura2017/tosca-parser.git
        cd tosca-parser
        git checkout develop
        pip install -r requirements.txt
        python setup.py install
        cd ..
    - name: Install dependencies
      run: |
        pip install -i https://test.pypi.org/simple/ --upgrade cotea==1.3.3
    - name: Install application
      run: |
        python setup.py install
    - name: Test with pytest
      run: |
        python -m unittest discover -s testing
